name: Build Simple

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Créer un artefact de test
        run: echo "Hello SLSA" > artefact.txt
